import { BadgeCheck, CalendarDays, Settings } from 'lucide-react'
import { FC, memo } from 'react'

const HowItWorks: FC = () => {
  return (
    <section id="how" className="py-14 md:py-20">
      <div className="mx-auto max-w-7xl px-6">
        <div className="max-w-2xl">
          <h2 className="text-2xl font-semibold tracking-tight md:text-3xl">
            How it works
          </h2>
          <p className="mt-3 text-slate-600">
            Set up your organization, invite your team, and let automation take
            care of the rest.
          </p>
        </div>

        <div className="mt-8 grid grid-cols-1 gap-6 md:grid-cols-3">
          <div className="rounded-md border border-slate-200 bg-white p-5">
            <div className="flex items-center gap-2 text-slate-800">
              <Settings className="h-5 w-5" />
              <span className="font-medium">1. Configure</span>
            </div>
            <p className="mt-2 text-sm text-slate-600">
              Create an organization, set user rates, leave policies, and sync
              your Google Calendar.
            </p>
          </div>
          <div className="rounded-md border border-slate-200 bg-white p-5">
            <div className="flex items-center gap-2 text-slate-800">
              <CalendarDays className="h-5 w-5" />
              <span className="font-medium">2. Manage leave</span>
            </div>
            <p className="mt-2 text-sm text-slate-600">
              Admins register leave days or review requests. Events are
              auto-added to shared calendars.
            </p>
          </div>
          <div className="rounded-md border border-slate-200 bg-white p-5">
            <div className="flex items-center gap-2 text-slate-800">
              <BadgeCheck className="h-5 w-5" />
              <span className="font-medium">3. Auto-invoice</span>
            </div>
            <p className="mt-2 text-sm text-slate-600">
              Invoices are generated by period, rate, and days. Members approve,
              orgs are notified to pay.
            </p>
          </div>
        </div>
      </div>
    </section>
  )
}

export default memo(HowItWorks)
